"""H3 (step 1, device) DiscoveryPolicy home-rule mutants: each must compile and make home-device/main.swift fail. usage: mutants.py ROOT"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import module
F = "iOSClient/DiscoveryPolicy.swift"
M = [
    ("rowWord: a homeTLS Mac without p shows its method in DEBUG (a downgrade)", F, "            return debug && !homeTLS ? .method(method) : .updateSill", "            return debug ? .method(method) : .updateSill"),
    ("rowWord: Release shows a plain door's method", F, "            return debug && !homeTLS ? .method(method) : .updateSill", "            return !homeTLS ? .method(method) : .updateSill"),
    ("rowWord: revoked ignored", F, "            if saved && !revoked { return .method(method) }", "            if saved { return .method(method) }"),
    ("rowWord: an open door hides a revoked Mac's state", F, "            if !saved && door == .open { return .method(method) }", "            if door == .open { return .method(method) }"),
    ("rowWord: an unsaved Mac on an open door reads Not paired", F, "            if !saved && door == .open { return .method(method) }\n", ""),
    ("rowWord: the cable without the Wired word", F, "            return method == .wired && cable ? .pairsOverCable : .notPaired", "            return cable ? .pairsOverCable : .notPaired"),
    ("rowWord: every Wired row pairs over the cable", F, "            return method == .wired && cable ? .pairsOverCable : .notPaired", "            return method == .wired ? .pairsOverCable : .notPaired"),
    ("homeDial: a homeTLS Mac dialed plain in DEBUG", F, "            return debug && !homeTLS ? .plain : .updateSill", "            return debug ? .plain : .updateSill"),
    ("homeDial: Release dials plain", F, "            return debug && !homeTLS ? .plain : .updateSill", "            return !homeTLS ? .plain : .updateSill"),
    ("homeDial: revoked dialed pinned", F, "            if saved { return revoked ? (tap ? .ask(pinned: true) : .waitForTap) : .pinned }", "            if saved { return .pinned }"),
    ("homeDial: a revoked Mac's ask takes any key", F, "revoked ? (tap ? .ask(pinned: true) : .waitForTap) : .pinned", "revoked ? (tap ? .ask(pinned: false) : .waitForTap) : .pinned"),
    ("homeDial: the reconnect asks a revoked Mac", F, "revoked ? (tap ? .ask(pinned: true) : .waitForTap) : .pinned", "revoked ? .ask(pinned: true) : .pinned"),
    ("homeDial: the reconnect asks an unsaved Mac", F, "            return tap ? .ask(pinned: false) : .waitForTap", "            return .ask(pinned: false)"),
    ("homeDial: an open door asks", F, "            if door == .open { return .anyKey }\n", ""),
    ("homeDial: a required door takes any key", F, "            if door == .open { return .anyKey }", "            if door == .open || door == .pairingRequired { return .anyKey }"),
    ("onCable: IPv4 link-local counts", F, "        guard mac.count == 16, isLinkLocal(mac) else {", "        guard isLinkLocal(mac) else {"),
    ("onCable: any IPv6 counts", F, "        guard mac.count == 16, isLinkLocal(mac) else {", "        guard mac.count == 16 else {"),
    ("onCable: any interface type", F, "        guard scope.type == .wiredEthernet, !isPeerToPeer(scope.name) else {", "        guard !isPeerToPeer(scope.name) else {"),
    ("onCable: AWDL by type only", F, "        guard scope.type == .wiredEthernet, !isPeerToPeer(scope.name) else {", "        guard scope.type == .wiredEthernet else {"),
    ("onCable: this device's own address not checked", F,
     "        guard !own.contains(where: { unscoped($0.address) == m }) else {\n            return CableCheck(cable: false, console: \"cable: no, \\(addressText(mac)) is this device\\u{2019}s own address\")\n        }\n", ""),
    ("onCable: own addresses compared with the embedded scope", F, "guard !own.contains(where: { unscoped($0.address) == m }) else {", "guard !own.contains(where: { $0.address == mac }) else {"),
    ("onCable: a routable address on the interface ignored", F,
     "        if let routable = mine.first(where: { !isLinkLocal($0) }) {\n            return CableCheck(cable: false, console: \"cable: no, \\(scope.name) has \\(addressText(routable))\")\n        }\n", ""),
    ("onCable: an interface with no address counts", F,
     "        guard !mine.isEmpty else {\n            return CableCheck(cable: false, console: \"cable: no, \\(scope.name) has no address\")\n        }\n", ""),
    ("onCable: another interface's addresses judged", F, "        let mine = own.filter { $0.interface == scope.name }.map(\\.address)", "        let mine = own.map(\\.address).filter { _ in true }.prefix(3).map { $0 }"),
    ("carriesOnlyLinkLocal: an empty interface counts", F, "        return !mine.isEmpty && mine.allSatisfy(isLinkLocal)", "        return mine.allSatisfy(isLinkLocal)"),
    ("carriesOnlyLinkLocal: any link-local address is enough", F, "        return !mine.isEmpty && mine.allSatisfy(isLinkLocal)", "        return mine.contains(where: isLinkLocal)"),
    ("isLinkLocal: 169/8", F, "        if a.count == 4 { return a[0] == 169 && a[1] == 254 }", "        if a.count == 4 { return a[0] == 169 }"),
    ("isLinkLocal: fe80::/9", F, "        if a.count == 16 { return a[0] == 0xFE && a[1] & 0xC0 == 0x80 }", "        if a.count == 16 { return a[0] == 0xFE && a[1] & 0x80 == 0x80 }"),
    ("label: Not paired capitalised", F, "            if self == .notPaired { return \"\\(name), not paired\" }\n", ""),
    ("hint: Update Sill names no device", F, "            case .updateSill: return \"\\(name)\\u{2019}s Sill is too old for this \\(device).\"",
     "            case .updateSill: return \"\\(name)\\u{2019}s Sill is too old.\""),
    ("word: Not paired lower case", F, "            case .notPaired: return \"Not paired\"", "            case .notPaired: return \"not paired\""),
    # Step 4: sessions and pairing at home over TLS.
    ("pin: an open door's first connection plain", F, "        case .open(nil): return .anyKey", "        case .open(nil): return .plainTCP"),
    ("pin: an open session's later connections take any key", F, "        case .open(let seen?): return .key(seen)", "        case .open(let seen?): return seen.isEmpty ? .key(seen) : .anyKey"),
    ("pin: a saved Mac's session takes any key", F, "        case .saved(let pin): return .key(pin)", "        case .saved(let pin): return pin.isEmpty ? .key(pin) : .anyKey"),
    ("tls: an open session counted as plain", F, "        var tls: Bool { self != .plain }", "        var tls: Bool { if case .saved = self { return true }; return false }"),
    ("sessionTrust: an open door dialed plain", F, "        case .anyKey: return .open(seen: nil)", "        case .anyKey: return .plain"),
    ("sessionTrust: a saved Mac without a readable pin dialed with any key", F, "        case .pinned: return savedPin.map { .saved(pin: $0) }",
     "        case .pinned: return savedPin.map { .saved(pin: $0) } ?? .open(seen: nil)"),
    ("sessionTrust: the ask starts a session", F, "        case .ask, .updateSill, .waitForTap: return nil", "        case .ask: return .open(seen: nil)\n        case .updateSill, .waitForTap: return nil"),
    ("sessionTrust: a Mac too old dialed plain", F, "        case .ask, .updateSill, .waitForTap: return nil", "        case .updateSill: return .plain\n        case .ask, .waitForTap: return nil"),
    ("readyWith: a later connection's key replaces the first", F, "        if case .open(nil) = trust, let fingerprint { return .open(seen: fingerprint) }",
     "        if case .open = trust, let fingerprint { return .open(seen: fingerprint) }"),
    ("readyWith: an open session never keeps its key", F, "        if case .open(nil) = trust, let fingerprint { return .open(seen: fingerprint) }\n", ""),
    ("homeEnd: a plain door's goodbye read as removed", F, "        guard let trust, trust.tls else { return .other }", "        guard let trust else { return .other }"),
    ("homeEnd: removed not read", F, "        if goodbye == \"removed\" { return .removed }\n", ""),
    ("homeEnd: pairingRequired not read", F, "        if goodbye == \"pairingRequired\" { return .pairingRequired }\n", ""),
    ("homeEnd: a TLS error beside another goodbye", F, "        guard goodbye == nil, let tls else { return .other }", "        guard let tls else { return .other }"),
    ("homeEnd: a refused key never revokes", F, "            if keyRefused.contains(tls) { return .removed }\n", ""),
    ("homeEnd: a pin failure not told", F, "            return tls == pinRefused ? .wrongKey : .other", "            return .other"),
    ("homeEnd: an open session's refused key read as removed", F, "            return keyRefused.contains(tls) ? .pairingRequired : .other", "            return keyRefused.contains(tls) ? .removed : .other"),
    ("homeEnd: -9829 not a refusal", F, "    static let keyRefused: Set<Int32> = [-9825, -9829]", "    static let keyRefused: Set<Int32> = [-9825]"),
    ("nextPinnedRow: a tried row again", F, "        rows.first { $0.macID == macID && !tried.contains($0.id) }?.id", "        rows.first { $0.macID == macID }?.id"),
    ("nextPinnedRow: any row, tagged or not", F, "        rows.first { $0.macID == macID && !tried.contains($0.id) }?.id", "        rows.first { ($0.macID == macID || $0.macID == nil) && !tried.contains($0.id) }?.id"),
    ("askAnswer: the cable's ok without the device's claim", F, "            guard method == \"cable\", askedCable, !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }",
     "            guard method == \"cable\", !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }"),
    ("askAnswer: any ok taken", F, "            guard method == \"cable\", askedCable, !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }",
     "            guard askedCable, !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }"),
    ("askAnswer: another Mac's ID taken", F, "            guard method == \"cable\", askedCable, !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }",
     "            guard method == \"cable\", askedCable, !hasProof, recognitionKeyBytes == 32 else { return .invalid }"),
    ("askAnswer: an ok with a proof taken", F, "            guard method == \"cable\", askedCable, !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }",
     "            guard method == \"cable\", askedCable, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }"),
    ("askAnswer: any recognition key", F, "            guard method == \"cable\", askedCable, !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }",
     "            guard method == \"cable\", askedCable, !hasProof, macIDMatches, recognitionKeyBytes != nil else { return .invalid }"),
    ("askAnswer: shown read as openOnMac", F, "        case \"shown\"?: return .shown", "        case \"shown\"?: return .openOnMac"),
    ("askAnswer: locked read as refused", F, "        case \"locked\"?: return .locked\n", ""),
    ("askAnswer: busy unbounded", F, "        case \"busy\"?: return .busy(min(max(retryAfter ?? 1, 0.2), 10))", "        case \"busy\"?: return .busy(retryAfter ?? 1)"),
    ("askAnswer: an unknown reason read as shown", F, "        default: return .refused\n        }\n    }\n\n    /// Where a pairing link", "        default: return .shown\n        }\n    }\n\n    /// Where a pairing link"),
    ("linkRows: the asked key goes to every row", F, "        if let askedKey, askedKey == linkKey { return nil }\n", ""),
    ("linkRows: plain doors dialed", F, "        return rows.filter { $0.door != .plain && !(askedKey != nil && $0.id == askedRow) }.map(\\.id)",
     "        return rows.filter { !(askedKey != nil && $0.id == askedRow) }.map(\\.id)"),
    ("linkRows: the asked row not left out", F, "        return rows.filter { $0.door != .plain && !(askedKey != nil && $0.id == askedRow) }.map(\\.id)",
     "        return rows.filter { $0.door != .plain }.map(\\.id)"),
    ("copy: over the cable dropped", F, "            cable ? \"Pairing with \\(mac) over the cable\\u{2026}\" : \"Pairing with \\(mac)\\u{2026}\"", "            \"Pairing with \\(mac)\\u{2026}\""),
    ("copy: removed says the old remote words", F, "        static func removed(mac: String, device: String) -> String { \"\\(mac) removed this \\(device). Tap it to pair again.\" }",
     "        static func removed(mac: String, device: String) -> String { \"\\(mac) removed this \\(device). To use it again, pair it again.\" }"),
    ("copy: openOnMac names no menu", F, "\"\\(mac) didn\\u{2019}t show a code. On the Mac, choose Pair iPhone or iPad\\u{2026} in the Sill menu, then tap \\(mac) again.\"",
     "\"\\(mac) didn\\u{2019}t show a code.\""),
    # Step 5: the Settings panel's Away from home, and the words of the home card and the overlay at home.
    ("away: a saved Mac's footnote ignores the remote session", F,
     "        if saved { return .paired(remoteSession ? .connected : remoteAccess ? .reaches : .turnOnRemoteAccess) }",
     "        if saved { return .paired(remoteAccess ? .reaches : .turnOnRemoteAccess) }"),
    ("away: a saved Mac always reaches from afar (Remote Access ignored)", F,
     "        if saved { return .paired(remoteSession ? .connected : remoteAccess ? .reaches : .turnOnRemoteAccess) }",
     "        if saved { return .paired(remoteSession ? .connected : .reaches) }"),
    ("away: a saved Mac at home offered Pair This iPad…", F,
     "        if saved { return .paired(remoteSession ? .connected : remoteAccess ? .reaches : .turnOnRemoteAccess) }",
     "        if saved && remoteSession { return .paired(.connected) }"),
    ("away: pairing at home gated on Remote Access", F, "        if tlsAtHome && !remoteSession { return .pairThisDevice(atHome: true) }",
     "        if tlsAtHome && remoteAccess && !remoteSession { return .pairThisDevice(atHome: true) }"),
    ("away: a session over TLS pairs through the remote door", F, "        if tlsAtHome && !remoteSession { return .pairThisDevice(atHome: true) }",
     "        if tlsAtHome && !remoteSession { return .pairThisDevice(atHome: false) }"),
    ("away: a session over TLS treated as a plain one", F, "        if tlsAtHome && !remoteSession { return .pairThisDevice(atHome: true) }\n", ""),
    ("away: a remote session pairs at home", F, "        if tlsAtHome && !remoteSession { return .pairThisDevice(atHome: true) }",
     "        if tlsAtHome { return .pairThisDevice(atHome: true) }"),
    ("away: Remote Access off still offers the remote door", F, "        return remoteAccess ? .pairThisDevice(atHome: false) : .turnOnRemoteAccess",
     "        return .pairThisDevice(atHome: false)"),
    ("copy: the card's title says Add a Mac", F, "static func cardTitle(mac: String) -> String { \"Pair with \\(mac)\" }",
     "static func cardTitle(mac: String) -> String { \"Add a Mac\" }"),
    ("copy: the typed line asks for the address too", F, "static func typeCode(mac: String) -> String { \"Type the code \\(mac) shows.\" }",
     "static func typeCode(mac: String) -> String { \"Type the address and code from your Mac.\" }"),
    ("copy: the viewfinder names no Mac", F, "static func viewfinderCaption(mac: String) -> String { \"Point at the code on \\(mac)\" }",
     "static func viewfinderCaption(mac: String) -> String { \"Point at the code on your Mac\" }"),
    ("copy: over a stream, tap it again", F, "static func noAnswerOverStream(mac: String) -> String { \"\\(mac) didn\\u{2019}t answer. Try again.\" }",
     "static func noAnswerOverStream(mac: String) -> String { noAnswer(mac: mac) }"),
    ("copy: over a stream, the card's proof words", F, "            \"Pairing didn\\u{2019}t finish: \\(mac) couldn\\u{2019}t show it knows the code.\"\n",
     "            proofFailed(mac: mac)\n"),
]
sys.exit(0 if module.mutate("home-device", M, sys.argv[1]) else 1)
