#!/bin/bash
# Builds the pacing harness's two hosts (run.sh's first step; see its header): BASE's
# Sources/SillHost/StreamServer.swift and the working tree's, each with the neighbours it compiles
# with, its own Sources/StreamProtocol and Scripts/pacing/main.swift (the fake encoder), as two
# throwaway SwiftPM packages under .build/pacing/{base,new} (git-ignored). Nothing is copied into
# the repository, so nothing drifts. A file is rewritten only when it changed, so a second build is
# quick. Refuses a binary that links VideoToolbox, ScreenCaptureKit, CoreMedia or AVFoundation: the
# harness never touches the Mac's encoder.
#   Scripts/pacing/build.sh [BASE]     BASE: a commit, branch or tag (default origin/main)
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../.." && pwd)"
out="$root/.build/pacing"
base="${1:-origin/main}"
cd "$root"
git rev-parse --verify --quiet "$base^{commit}" > /dev/null || { echo "build.sh: no commit '$base'" >&2; exit 2; }

# StreamServer.swift and what it compiles with (a file BASE lacks is left out; if StreamServer
# needed it, the build says so).
host_files=(StreamServer ClientLink DeviceGate HostLog InterfaceSnapshot OriginPolicy PointerControl PointerWatch RefusalSummary Stats)
# The Mac's sound (docs/audio-plan.md H6): where a side has these, they are compiled in with SILL_AUDIO
# defined, and main.swift's --audio runs the test tone through the real pipeline and send path.
audio_files=(AudioPipeline AudioPacketizer AudioEncoder SyntheticAudio TestTone)

# put DEST: stdin to DEST, only if it differs.
put() {
    local dest="$1" tmp
    tmp="$(mktemp "$out/.put.XXXXXX")"
    cat > "$tmp"
    if cmp -s "$tmp" "$dest" 2> /dev/null; then rm -f "$tmp"; else mkdir -p "$(dirname "$dest")"; mv "$tmp" "$dest"; fi
}

# side NAME REF: the package for REF ("" = the working tree).
side() {
    local name="$1" ref="$2" pkg="$out/$1" f keep=() sound=1 settings=""
    mkdir -p "$pkg/Sources/StreamProtocol" "$pkg/Sources/Harness"
    for f in "${audio_files[@]}"; do
        if [ -z "$ref" ]; then [ -f "Sources/SillHost/$f.swift" ] || sound=0
        else git cat-file -e "$ref:Sources/SillHost/$f.swift" 2> /dev/null || sound=0; fi
    done
    [ "$sound" = 1 ] && settings=', swiftSettings: [.define("SILL_AUDIO")]'
    put "$pkg/Package.swift" <<SWIFT
// swift-tools-version:5.9
// Generated by Scripts/pacing/build.sh: the pacing harness's host. Named "sill" like the real
// package, so the host files' \`package\` access compiles unchanged.
import PackageDescription
let package = Package(
    name: "sill",
    platforms: [.macOS(.v14)],
    targets: [
        .target(name: "StreamProtocol"),
        .executableTarget(name: "Harness", dependencies: ["StreamProtocol"]$settings),
    ]
)
SWIFT
    # StreamProtocol, whole.
    if [ -z "$ref" ]; then
        for f in Sources/StreamProtocol/*.swift; do put "$pkg/$f" < "$f"; keep+=("$pkg/$f"); done
    else
        while IFS= read -r f; do
            case "$f" in *.swift) git show "$ref:$f" | put "$pkg/$f"; keep+=("$pkg/$f") ;; esac
        done < <(git ls-tree --name-only "$ref" Sources/StreamProtocol/)
    fi
    local files=("${host_files[@]}")
    [ "$sound" = 1 ] && files+=("${audio_files[@]}")
    for f in "${files[@]}"; do
        local src="Sources/SillHost/$f.swift" dest="$pkg/Sources/Harness/$f.swift"
        if [ -z "$ref" ]; then
            [ -f "$src" ] || continue
            put "$dest" < "$src"
        else
            git cat-file -e "$ref:$src" 2> /dev/null || continue
            git show "$ref:$src" | put "$dest"
        fi
        keep+=("$dest")
    done
    put "$pkg/Sources/Harness/main.swift" < "$here/main.swift"
    keep+=("$pkg/Sources/Harness/main.swift")
    # Whatever an earlier build left that this one does not have.
    while IFS= read -r f; do
        local k found=0
        for k in "${keep[@]}"; do [ "$k" = "$f" ] && found=1 && break; done
        [ "$found" = 1 ] || rm -f "$f"
    done < <(find "$pkg/Sources" -name '*.swift')
    echo "==> $name: StreamServer.swift of ${ref:-the working tree} (md5 $(md5 -q "$pkg/Sources/Harness/StreamServer.swift"))$([ "$sound" = 1 ] && echo ", with the sound")"
    if ! swift build -c release --package-path "$pkg" > "$out/$name-build.log" 2>&1; then
        grep -E 'error:' "$out/$name-build.log" | head -20 >&2 || true
        echo "build.sh: the $name harness did not build; the log is $out/$name-build.log" >&2
        exit 1
    fi
    local bin="$pkg/.build/release/Harness"
    if otool -L "$bin" | grep -Eq 'VideoToolbox|ScreenCaptureKit|CoreMedia|AVFoundation'; then
        echo "build.sh: $bin links a media framework; refusing it" >&2
        rm -f "$bin"
        exit 1
    fi
    echo "    $bin"
}

mkdir -p "$out"
side base "$base"
side new ""
