#!/bin/bash
# Builds the encoder-free sound harness (docs/audio-plan.md §11; run.sh's first step):
#   - the host: the working tree's Sources/SillHost/StreamServer.swift with the neighbours it compiles
#     with (Scripts/pacing/build.sh's list) and the sound's host files (AudioPipeline, AudioPacketizer,
#     AudioEncoder, SyntheticAudio, TestTone), its Sources/StreamProtocol and Scripts/audio/main.swift,
#     as a throwaway SwiftPM package under .build/audio/host (git-ignored); named "sill" like the real
#     package, so the host files' `package` access compiles unchanged;
#   - the device: Scripts/audiocheck.swift with Sources/StreamProtocol, iOSClient/AudioDecoder.swift,
#     iOSClient/AudioPlayout.swift and Sources/SillHost/TestTone.swift as one module (swiftc),
#     .build/audio/audiocheck.
# Nothing is copied into the repository, and a file is rewritten only when it changed, so a second build
# is quick. Refuses a binary that links VideoToolbox, ScreenCaptureKit, CoreMedia or AVFoundation: the
# harness never touches the Mac's encoder, never captures sound and never plays any.
#   Scripts/audio/build.sh
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../.." && pwd)"
out="$root/.build/audio"
cd "$root"
host_files=(StreamServer ClientLink DeviceGate HostLog InterfaceSnapshot OriginPolicy PointerControl PointerWatch RefusalSummary Stats
            AudioPipeline AudioPacketizer AudioEncoder SyntheticAudio TestTone)

put() {   # put DEST: stdin to DEST, only if it differs
    local dest="$1" tmp
    tmp="$(mktemp "$out/.put.XXXXXX")"
    cat > "$tmp"
    if cmp -s "$tmp" "$dest" 2> /dev/null; then rm -f "$tmp"; else mkdir -p "$(dirname "$dest")"; mv "$tmp" "$dest"; fi
}
refuse_media() {
    if otool -L "$1" | grep -Eq 'VideoToolbox|ScreenCaptureKit|CoreMedia|AVFoundation'; then
        echo "build.sh: $1 links a media framework; refusing it" >&2
        rm -f "$1"
        exit 1
    fi
}

mkdir -p "$out"
pkg="$out/host" keep=()
mkdir -p "$pkg/Sources/StreamProtocol" "$pkg/Sources/Harness"
put "$pkg/Package.swift" <<'SWIFT'
// swift-tools-version:5.9
// Generated by Scripts/audio/build.sh: the sound harness's host.
import PackageDescription
let package = Package(
    name: "sill",
    platforms: [.macOS(.v14)],
    targets: [
        .target(name: "StreamProtocol"),
        .executableTarget(name: "Harness", dependencies: ["StreamProtocol"]),
    ]
)
SWIFT
for f in Sources/StreamProtocol/*.swift; do put "$pkg/$f" < "$f"; keep+=("$pkg/$f"); done
for f in "${host_files[@]}"; do put "$pkg/Sources/Harness/$f.swift" < "Sources/SillHost/$f.swift"; keep+=("$pkg/Sources/Harness/$f.swift"); done
put "$pkg/Sources/Harness/main.swift" < "$here/main.swift"
keep+=("$pkg/Sources/Harness/main.swift")
while IFS= read -r f; do
    k="" found=0
    for k in "${keep[@]}"; do [ "$k" = "$f" ] && found=1 && break; done
    [ "$found" = 1 ] || rm -f "$f"
done < <(find "$pkg/Sources" -name '*.swift')
if ! swift build -c release --package-path "$pkg" > "$out/host-build.log" 2>&1; then
    grep -E 'error:' "$out/host-build.log" | head -20 >&2 || true
    echo "build.sh: the harness's host did not build; the log is $out/host-build.log" >&2
    exit 1
fi
refuse_media "$pkg/.build/release/Harness"
echo "    $pkg/.build/release/Harness"

dev="$out/device"
mkdir -p "$dev"
for f in Sources/StreamProtocol/*.swift; do put "$dev/$(basename "$f")" < "$f"; done
put "$dev/AudioDecoder.swift" < iOSClient/AudioDecoder.swift
put "$dev/AudioPlayout.swift" < iOSClient/AudioPlayout.swift
put "$dev/TestTone.swift" < Sources/SillHost/TestTone.swift
put "$dev/main.swift" < Scripts/audiocheck.swift
if ! swiftc -O "$dev"/*.swift -o "$out/audiocheck" > "$out/audiocheck-build.log" 2>&1; then
    grep -E 'error:' "$out/audiocheck-build.log" | head -20 >&2 || true
    echo "build.sh: audiocheck did not build; the log is $out/audiocheck-build.log" >&2
    exit 1
fi
refuse_media "$out/audiocheck"
echo "    $out/audiocheck"
