"""H3 (step 1) DoorPolicy mutants: each must compile and make door-policy/main.swift fail. usage: mutants.py ROOT"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import module
F = "Sources/SillHost/DoorPolicy.swift"
M = [
    ("kind 19 of a later generation judged as this one's", F, "        guard version == PairRequest.version else { return .closed }\n", ""),
    ("kind 19: only a higher generation is closed", F, "        guard version == PairRequest.version else { return .closed }", "        guard version <= PairRequest.version else { return .closed }"),
    ("remote door ignores Require pairing too", F, "return door == .home ? t.paired || !t.requirePairing : t.paired", "return t.paired || !t.requirePairing"),
    ("home sill/1 needs a paired key even with Require pairing off", F, "return door == .home ? t.paired || !t.requirePairing : t.paired", "return t.paired"),
    ("remote pairing takes any window, as before this change", F, "return door == .home ? true : t.remotePairingOpen", "return door == .home ? true : t.pairingOpen"),
    ("home pairing needs an open window", F, "return door == .home ? true : t.remotePairingOpen", "return door == .home ? t.pairingOpen : t.remotePairingOpen"),
    ("a peer without a key is trusted", F, "        guard t.hasKey else { return false }\n        switch alpn {", "        switch alpn {"),
    ("an unknown ALPN is trusted at home", F, "        default:\n            return false\n        }\n    }\n\n    // MARK: At `.ready`",
     "        default:\n            return door == .home\n        }\n    }\n\n    // MARK: At `.ready`"),
    ("at .ready: no key check", F, "        guard t.hasKey else { return .refuse(\"unpaired\") }\n        switch (door, alpn) {", "        switch (door, alpn) {"),
    ("at .ready: home sill/1 not checked again", F, "return trusts(.home, alpn: alpn, t) ? .session : .refuse(\"unpaired\")", "return .session"),
    ("at .ready: home pairing refused without a window", F, "        case (.home, RemoteTLS.pairingALPN?):\n            return .pairing",
     "        case (.home, RemoteTLS.pairingALPN?):\n            return t.pairingOpen ? .pairing : .refuse(\"unpaired\")"),
    ("at .ready: busy at 9, not 8", F, "guard remoteSessions < maxRemoteSessions else", "guard remoteSessions <= maxRemoteSessions else"),
    ("at .ready: busy before remoteOff", F,
     "            guard t.remoteAccess else { return .goodbye(Goodbye.remoteOff) }\n            guard remoteSessions < maxRemoteSessions else { return .goodbye(Goodbye.busy) }",
     "            guard remoteSessions < maxRemoteSessions else { return .goodbye(Goodbye.busy) }\n            guard t.remoteAccess else { return .goodbye(Goodbye.remoteOff) }"),
    ("at .ready: remote pairing on any window", F, "return t.remotePairingOpen ? .pairing : .refuse(\"unpaired\")", "return t.pairingOpen || t.remotePairingOpen ? .pairing : .refuse(\"unpaired\")"),
    ("at .ready: the home door has a session limit", F, "        case (.home, RemoteTLS.sessionALPN?):\n            return trusts(.home, alpn: alpn, t) ? .session : .refuse(\"unpaired\")",
     "        case (.home, RemoteTLS.sessionALPN?):\n            guard remoteSessions < maxRemoteSessions else { return .goodbye(Goodbye.busy) }\n            return trusts(.home, alpn: alpn, t) ? .session : .refuse(\"unpaired\")"),
    ("kind 19: an ask at the remote door goes to the window", F, "return door == .home ? .ask : .closed", "return door == .home ? .ask : .window"),
    ("kind 19: an ask at the remote door runs the ask rule", F, "return door == .home ? .ask : .closed", "return .ask"),
    ("handshake: -9836 is an older Sill at the remote door too", F, "case -9836 where door == .home: return .olderSill", "case -9836: return .olderSill"),
    ("handshake: an older Sill counts toward the backoff", F, "case -9836 where door == .home: return .olderSill", "case -9836 where door == .home: return .refused(\"older\")"),
    ("handshake: an HTTP request is an older Sill", F, "case -9836 where door == .home: return .olderSill", "case -9836 where door == .home, -9858 where door == .home: return .olderSill"),
    ("handshake: -9825 (the peer refused our key) counts", F, "case -9808, -9863, -9810, -9836, -9858: return .refused(\"unpaired\")", "case -9808, -9863, -9810, -9836, -9858, -9825: return .refused(\"unpaired\")"),
    ("ask: step 2 without the device's claim", F, "if cableSeen && cableClaimed && !otherKeyOfDevice { return .pairNow }", "if cableSeen && !otherKeyOfDevice { return .pairNow }"),
    ("ask: step 2 on the claim alone", F, "if cableSeen && cableClaimed && !otherKeyOfDevice { return .pairNow }", "if cableClaimed && !otherKeyOfDevice { return .pairNow }"),
    ("ask: step 2 ignores another key of the device", F, "if cableSeen && cableClaimed && !otherKeyOfDevice { return .pairNow }", "if cableSeen && cableClaimed { return .pairNow }"),
    ("ask: the cable before the lock", F, "        if !unlocked { return .locked }\n        if cableSeen && cableClaimed && !otherKeyOfDevice { return .pairNow }",
     "        if cableSeen && cableClaimed && !otherKeyOfDevice { return .pairNow }\n        if !unlocked { return .locked }"),
    ("ask: an open window before the cable", F, "        if cableSeen && cableClaimed && !otherKeyOfDevice { return .pairNow }\n        if windowOpen { return .shown(opened: false) }",
     "        if windowOpen { return .shown(opened: false) }\n        if cableSeen && cableClaimed && !otherKeyOfDevice { return .pairNow }"),
    ("ask: this Mac before an open window", F, "        if windowOpen { return .shown(opened: false) }\n        if fromThisMac { return .openOnMac(\"this Mac\") }",
     "        if fromThisMac { return .openOnMac(\"this Mac\") }\n        if windowOpen { return .shown(opened: false) }"),
    ("ask: quiet before this Mac", F, "        if fromThisMac { return .openOnMac(\"this Mac\") }\n        if quiet { return .openOnMac(\"quiet\") }",
     "        if quiet { return .openOnMac(\"quiet\") }\n        if fromThisMac { return .openOnMac(\"this Mac\") }"),
    ("ask: an ask from this Mac opens a window", F, "        if fromThisMac { return .openOnMac(\"this Mac\") }\n", ""),
    ("ask: often at 4, not 3", F, "if recentDeviceWindows >= AskLimits.maxWindows", "if recentDeviceWindows > AskLimits.maxWindows"),
    ("ask: often before quiet", F, "        if quiet { return .openOnMac(\"quiet\") }\n        if recentDeviceWindows >= AskLimits.maxWindows { return .openOnMac(\"often\") }",
     "        if recentDeviceWindows >= AskLimits.maxWindows { return .openOnMac(\"often\") }\n        if quiet { return .openOnMac(\"quiet\") }"),
    ("reason: locked answered openOnMac", F, "case .locked: return PairResult.locked", "case .locked: return PairResult.openOnMac"),
    ("menu: an ask from this Mac lights it", F, "        if fromThisMac { return nil }\n        switch a {", "        switch a {"),
    ("menu: a window already open says showing", F, "case .pairNow, .shown(opened: false): return nil", "case .pairNow: return nil\n        case .shown(opened: false): return \"showing\""),
    ("from this Mac: loopback not counted", F, "        if IPBytes.isLoopback(s) { return true }\n", ""),
    ("from this Mac: link-local compared with the embedded scope", F, "return ownAddresses.contains { IPBytes.unscoped(IPBytes.unmapped($0)) == s }", "return ownAddresses.contains(source)"),
    ("from this Mac: an IPv4-mapped source not unmapped", F, "let s = IPBytes.unscoped(IPBytes.unmapped(source))", "let s = IPBytes.unscoped(source)"),
    ("other key: the same key counts as another", F, "paired.contains { $0.cableDevice == cableDevice && $0.fingerprint != fingerprint }", "paired.contains { $0.cableDevice == cableDevice }"),
    ("test host: the bundle honours hooks", F, "static func isTestHost(advertises: Bool, bundled: Bool) -> Bool { !advertises && !bundled }",
     "static func isTestHost(advertises: Bool, bundled: Bool) -> Bool { !advertises }"),
    ("the ask hook on any host", F, "        testHost && environment[\"SILL_TEST_ASK_FROM_THIS_MAC\"] == \"1\"", "        environment[\"SILL_TEST_ASK_FROM_THIS_MAC\"] == \"1\""),
    ("refusal word: a VPN counted as internet at home", F, "case .home: return origin == .vpn ? \"vpn\" : \"internet\"", "case .home: return \"internet\""),
    ("before start: the remote door ignores the internet switch", F, "case .remote: return OriginPolicy.remoteAdmits(origin, internetAccess: internetAccess)",
     "case .remote: return OriginPolicy.remoteAdmits(origin, internetAccess: true)"),
    ("before start: the home door takes the remote door's origins", F, "case .home: return OriginPolicy.homeAdmits(origin)", "case .home: return OriginPolicy.remoteAdmits(origin, internetAccess: internetAccess)"),
    # The merge with main's update notice: what a session the device gate held is judged by again.
    ("after the gate: a removed key admitted at the remote door", F, "            if !t.hasKey || !t.paired { return Goodbye.removed }\n", ""),
    ("after the gate: remote, the limit before Remote Access", F,
     ["            if !t.remoteAccess { return Goodbye.remoteOff }\n", "            if remoteSessions >= maxRemoteSessions { return Goodbye.busy }\n"],
     ["            if remoteSessions >= maxRemoteSessions { return Goodbye.busy }\n", "            if !t.remoteAccess { return Goodbye.remoteOff }\n"]),
    ("after the gate: remote, the internet switch ignored", F, "if !OriginPolicy.remoteAdmits(origin, internetAccess: t.internetAccess) { return Goodbye.internetOff }",
     "if !OriginPolicy.remoteAdmits(origin, internetAccess: true) { return Goodbye.internetOff }"),
    ("after the gate: remote, busy at 9", F, "            if remoteSessions >= maxRemoteSessions { return Goodbye.busy }", "            if remoteSessions > maxRemoteSessions { return Goodbye.busy }"),
    ("after the gate: home ignores Require pairing", F, "            return t.requirePairing ? Goodbye.pairingRequired : nil", "            return nil"),
    ("after the gate: home, removed read as pairingRequired", F, "            if wasPaired { return Goodbye.removed }", "            if wasPaired { return Goodbye.pairingRequired }"),
    ("after the gate: home drops a key paired meanwhile", F, "            if t.paired { return nil }", "            if t.paired && wasPaired { return nil }"),
    ("after the gate: home keeps a removed key while Require pairing is off", F, "            if wasPaired { return Goodbye.removed }\n", ""),
]
sys.exit(0 if module.mutate("door-policy", M, sys.argv[1]) else 1)
