"""(integrate-12: follow-best-path's 61 mutants, unchanged, and R1-R9 of the merge's remote rule, against the merged file and policy-merge/main.swift.) Each mutant of DiscoveryPolicy's session route (P: route, S: sessionRoute/describesFlow), of the wired dial (D: dialInterface, W: wiredWait), of following the best path (F: pathPlan, pathGone, PathSightings, freshWifi, wifiInterface, rank) and of its review fixes (G: the reconnect over the cable, the refused listing, upWait) must fail the policy check. usage: mutants.py"""
import os, subprocess, sys
SP = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(SP, "..", "..", ".."))   # the repository
OUT = os.path.join(ROOT, ".build", "checks", "policy")   # the mutants' sources and binaries
os.makedirs(OUT, exist_ok=True)
SRC = os.path.join(ROOT, "iOSClient/DiscoveryPolicy.swift")
orig = open(SRC).read()
MUTANTS = {
    "P1 first path interface wins": ("guard let first = each.first, each.allSatisfy({ $0 == first }) else { return nil }",
                                     "guard let first = each.first else { return nil }"),
    "P2 scope ignored": ("if let scope { return method(of: scope) }", "_ = scope"),
    "P3 peer-to-peer checked after the type": ("        if isPeerToPeer(interface.name) { return .direct }\n        switch interface.type {\n        case .wiredEthernet: return .wired\n        case .wifi: return .wifi\n",
                                               "        switch interface.type {\n        case .wiredEthernet: return .wired\n        case .wifi: return isPeerToPeer(interface.name) ? .direct : .wifi\n"),
    "P3b peer-to-peer never Direct": ("        if isPeerToPeer(interface.name) { return .direct }\n        switch interface.type {", "        switch interface.type {"),
    "P4 unknown types as Wi-Fi": ("case .cellular, .loopback, .other: return nil", "case .cellular, .loopback, .other: return .wifi"),
    "P5 wired Ethernet as Wi-Fi": ("        case .wiredEthernet: return .wired\n        case .wifi: return .wifi\n        case .cellular",
                                   "        case .wiredEthernet: return .wifi\n        case .wifi: return .wifi\n        case .cellular"),
    "P6 wordless interfaces ignored": ("let each = path.map(method(of:))", "let each = path.compactMap(method(of:))"),
    "P7 the scope only when it has a word": ("if let scope { return method(of: scope) }", "if let scope, let m = method(of: scope) { return m }"),
    # sessionRoute and describesFlow (the wired fix, 2026-09-25)
    "S1 every update read (the bug: describesFlow ignored)": ("        guard describesFlow else { return current }\n", ""),
    "S2 never re-read (always the current word)": ("        return route(scope: scope ?? local, path: path)\n", "        return current\n"),
    "S3 a fresh reading must also name the Mac": ("        fresh || (hasAddress && satisfied)\n", "        hasAddress && satisfied\n"),
    "S4 an update without the Mac's address counts": ("        fresh || (hasAddress && satisfied)\n", "        fresh || satisfied\n"),
    "S5 an unsatisfied update counts": ("        fresh || (hasAddress && satisfied)\n", "        fresh || hasAddress\n"),
    "S6 either witness counts": ("        fresh || (hasAddress && satisfied)\n", "        fresh || hasAddress || satisfied\n"),
    "S7 no update ever counts": ("        fresh || (hasAddress && satisfied)\n", "        fresh\n"),
    "S8 this device's address ignored": ("        return route(scope: scope ?? local, path: path)\n", "        return route(scope: scope, path: path)\n"),
    "S9 this device's address beats the Mac's scope": ("        return route(scope: scope ?? local, path: path)\n", "        return route(scope: local ?? scope, path: path)\n"),
    "S10 a reading with no word keeps the old one": ("        return route(scope: scope ?? local, path: path)\n", "        return route(scope: scope ?? local, path: path) ?? current\n"),
    # dialInterface and wiredWait (prefer-cable, 2026-09-25)
    "D1 a Direct row dialled on a wired interface": ("        guard !direct else { return nil }\n        return interfaces.first { $0.type == .wiredEthernet", "        return interfaces.first { $0.type == .wiredEthernet"),
    "D2 the first interface whatever its type": ("interfaces.first { $0.type == .wiredEthernet && !isPeerToPeer($0.name) }?.name",
                                                  "interfaces.first { !isPeerToPeer($0.name) }?.name"),
    "D3 the last wired interface": ("interfaces.first { $0.type == .wiredEthernet && !isPeerToPeer($0.name) }?.name",
                                     "interfaces.last { $0.type == .wiredEthernet && !isPeerToPeer($0.name) }?.name"),
    "D4 never pinned": ("        return interfaces.first { $0.type == .wiredEthernet && !isPeerToPeer($0.name) }?.name\n",
                        "        return nil\n"),
    "D5 Wi-Fi dialled too": ("interfaces.first { $0.type == .wiredEthernet && !isPeerToPeer($0.name) }?.name",
                             "interfaces.first { ($0.type == .wiredEthernet || $0.type == .wifi) && !isPeerToPeer($0.name) }?.name"),
    "D6 peer-to-peer names dialled": ("interfaces.first { $0.type == .wiredEthernet && !isPeerToPeer($0.name) }?.name",
                                      "interfaces.first { $0.type == .wiredEthernet }?.name"),
    "W1 the wired dial waits 5 s": ("    static let wiredWait = 2.5\n", "    static let wiredWait = 5.0\n"),
    # pathPlan, pathGone, PathSightings, wifiInterface (follow-best-path, 2026-09-25)
    "F1 the cable's settle ignored": ("        let settled = max(since, i.lastDown ?? since) + cableSettle\n",
                                      "        let settled = max(since, i.lastDown ?? since)\n"),
    "F2 no hysteresis up": ("            let due = max(settled, (i.lastUp ?? -.infinity) + upWait(failures: i.upFailures))\n", "            let due = settled\n"),
    "F3 no hysteresis down": ("        if let last = i.lastDown, i.now < last + pathHysteresis {\n", "        if let last = i.lastDown, i.now < last {\n"),
    "F4 Wi-Fi to Wi-Fi when Wi-Fi's path goes": ("        if route == .wifi { return .stay(gone ? .lost : .wifi, recheckAt: nil) }\n",
                                                 "        if route == .wifi && !gone { return .stay(.wifi, recheckAt: nil) }\n"),
    "F5 off a cable that works, to a listed Wi-Fi": ("        guard gone else {\n", "        guard gone || i.wifi != nil else {\n"),
    "F6 a Direct session moved to the cable": ("        if route == .direct { return .stay(.direct, recheckAt: nil) }\n", ""),
    "F7 reconnectNow without Wi-Fi": ("        guard let wifi = i.wifi else { return .stay(.noWifi, recheckAt: nil) }\n        if i.dead { return .reconnectNow(.wifi, interface: wifi) }\n",
                                      "        if i.dead { return .reconnectNow(.wifi, interface: i.wifi ?? \"en0\") }\n        guard let wifi = i.wifi else { return .stay(.noWifi, recheckAt: nil) }\n"),
    "F8 Wi-Fi still fresh at exactly 5 s": ("        if let left = s.wifiLeft[name], now - left.at < wifiFresh { return left.interface }\n",
                                            "        if let left = s.wifiLeft[name], now - left.at <= wifiFresh { return left.interface }\n"),
    "F9 pong silence while the browser lists the cable": ("        guard i.route == .wired, i.wired == nil else { return false }\n", "        guard i.route == .wired else { return false }\n"),
    "F10 a hint alone takes the session off the cable": ("        if i.dead || i.pathReported { return true }\n", "        if i.dead || i.pathReported || i.pathHinted { return true }\n"),
    "F11 a dead connection moved up": ("        if !i.dead, Method.wired.rank > route.rank, let wired = i.wired, let since = i.wiredSince {\n",
                                       "        if Method.wired.rank > route.rank, let wired = i.wired, let since = i.wiredSince {\n"),
    "F12 wifiInterface takes awdl0 or llw0": ("        return interfaces.first { $0.type == .wifi && !isPeerToPeer($0.name) }?.name\n",
                                              "        return interfaces.first { $0.type == .wifi }?.name\n"),
    "F13 a move down does not start the settle again": ("        let settled = max(since, i.lastDown ?? since) + cableSettle\n", "        let settled = since + cableSettle\n"),
    "F14 wiredSince starts again at every look": ("                next.wiredSince[entry.name] = previous.wiredSince[entry.name] ?? now\n",
                                                  "                next.wiredSince[entry.name] = now\n"),
    "F15 the Wi-Fi memory kept for one look only": ("        for (name, left) in previous.wifiLeft where next.wifi[name] == nil && next.wifiLeft[name] == nil && now - left.at < wifiFresh {\n            next.wifiLeft[name] = left\n        }\n", ""),
    "F16 freshWifi ignores the memory": ("        if let left = s.wifiLeft[name], now - left.at < wifiFresh { return left.interface }\n", ""),
    "F17 Wi-Fi ranked over the cable": ("            case .wired: return 2\n            case .wifi: return 1\n            case .direct: return 0\n",
                                        "            case .wired: return 1\n            case .wifi: return 2\n            case .direct: return 0\n"),
    "F18 no look again at the silence mark": ("            if i.wired == nil { return .stay(.cableUnlisted, recheckAt: i.lastPong + pongSilence) }\n",
                                              "            if i.wired == nil { return .stay(.cableUnlisted, recheckAt: nil) }\n"),
    "F19 the silence 2 s": ("    static let pongSilence = 1.0\n", "    static let pongSilence = 2.0\n"),
    "F20 the settle 1 s": ("    static let cableSettle = 2.0\n", "    static let cableSettle = 1.0\n"),
    "F21 the hysteresis 3 s": ("    static let pathHysteresis = 5.0\n", "    static let pathHysteresis = 3.0\n"),
    "F22 Wi-Fi fresh for 10 s": ("    static let wifiFresh = 5.0\n", "    static let wifiFresh = 10.0\n"),
    "F23 a dead session held back by the hysteresis": ("        if i.dead { return .reconnectNow(.wifi, interface: wifi) }\n        if let last = i.lastDown, i.now < last + pathHysteresis {\n            return .stay(.downTooSoon, recheckAt: last + pathHysteresis)\n        }\n",
                                                      "        if let last = i.lastDown, i.now < last + pathHysteresis {\n            return .stay(.downTooSoon, recheckAt: last + pathHysteresis)\n        }\n        if i.dead { return .reconnectNow(.wifi, interface: wifi) }\n"),
    # review fixes (follow-best-path, 2026-09-25)
    "G1 a dead cable session always over Wi-Fi (the finding)": ("        if i.dead, !i.pathReported, let wired = i.wired { return .reconnectNow(.wired, interface: wired) }\n", ""),
    "G2 over the cable again though iOS said its path went": ("        if i.dead, !i.pathReported, let wired = i.wired {", "        if i.dead, let wired = i.wired {"),
    "G3 a hint counts against the cable": ("        if i.dead, !i.pathReported, let wired = i.wired {", "        if i.dead, !i.pathReported, !i.pathHinted, let wired = i.wired {"),
    "G4 over the cable again only with Wi-Fi listed": ("        if i.dead, !i.pathReported, let wired = i.wired { return .reconnectNow(.wired, interface: wired) }\n        guard let wifi = i.wifi else { return .stay(.noWifi, recheckAt: nil) }\n",
                                                       "        guard let wifi = i.wifi else { return .stay(.noWifi, recheckAt: nil) }\n        if i.dead, !i.pathReported, let wired = i.wired { return .reconnectNow(.wired, interface: wired) }\n"),
    "G5 over the cable again, named by Wi-Fi's interface": ("return .reconnectNow(.wired, interface: wired) }", "return .reconnectNow(.wired, interface: i.wifi ?? wired) }"),
    "G6 a refused listing tried again": ("            if since == i.refusedCable { return .stay(.cableRefused, recheckAt: nil) }\n", ""),
    "G7 a refused listing blocks every listing": ("            if since == i.refusedCable {", "            if i.refusedCable != nil {"),
    "G8 no back-off": ("        min(pathHysteresis * Double(1 << min(max(failures, 0), 4)), upBackoffCap)\n", "        pathHysteresis\n"),
    "G9 a back-off without its cap": ("        min(pathHysteresis * Double(1 << min(max(failures, 0), 4)), upBackoffCap)\n", "        pathHysteresis * Double(1 << min(max(failures, 0), 4))\n"),
    "G10 the back-off a step ahead": ("        min(pathHysteresis * Double(1 << min(max(failures, 0), 4)), upBackoffCap)\n", "        min(pathHysteresis * Double(1 << min(max(failures, 0) + 1, 4)), upBackoffCap)\n"),
    "G11 the cap 30 s": ("    static let upBackoffCap = 60.0\n", "    static let upBackoffCap = 30.0\n"),
    "G12 the failures ignored by the plan": ("(i.lastUp ?? -.infinity) + upWait(failures: i.upFailures))", "(i.lastUp ?? -.infinity) + upWait(failures: 0))"),
    "G13 the back-off's reason always the hysteresis": ("(i.upFailures > 0 ? .cableFailing : .upTooSoon)", ".upTooSoon"),
    # the merge with main (PR #13, remote access): a remote session is no candidate for the moves
    "R1 the remote rule dropped": ("        if i.remote { return .stay(.remote, recheckAt: nil) }\n", ""),
    "R2 remote only when the route says nothing": ("        if i.remote { return .stay(.remote, recheckAt: nil) }\n",
                                                   "        if i.remote, i.route == nil { return .stay(.remote, recheckAt: nil) }\n"),
    "R3 remote checked after a route that says nothing and Direct": (
        "        if i.remote { return .stay(.remote, recheckAt: nil) }\n        guard let route = i.route else { return .stay(.routeUnknown, recheckAt: nil) }\n        if route == .direct { return .stay(.direct, recheckAt: nil) }\n",
        "        guard let route = i.route else { return .stay(.routeUnknown, recheckAt: nil) }\n        if route == .direct { return .stay(.direct, recheckAt: nil) }\n        if i.remote { return .stay(.remote, recheckAt: nil) }\n"),
    "R4 a dead remote session made again here": ("        if i.remote { return .stay(.remote, recheckAt: nil) }\n",
                                                 "        if i.remote, !i.dead { return .stay(.remote, recheckAt: nil) }\n"),
    "R5 a remote session looks again": ("        if i.remote { return .stay(.remote, recheckAt: nil) }\n",
                                        "        if i.remote { return .stay(.remote, recheckAt: i.now + pathHysteresis) }\n"),
    "R6 the remote reason is Direct's": ("        if i.remote { return .stay(.remote, recheckAt: nil) }\n",
                                         "        if i.remote { return .stay(.direct, recheckAt: nil) }\n"),
    "R7 the reason's words": ('            case .remote: return "a remote session moves only home, once the network lists its Mac"\n',
                              '            case .remote: return "over Direct, the session moves only to the network"\n'),
    "R8 every session remote by default": ("        var remote = false\n", "        var remote = true\n"),
    "R9 a remote session read as its route word (the flag ignored)": ("        if i.remote { return .stay(.remote, recheckAt: nil) }\n",
                                                                      "        if i.remote && i.route == .direct { return .stay(.remote, recheckAt: nil) }\n"),
    # moveHome (remote-bundle, H15)
    "H1 the move home dials a refused row": ("        for row in rows where !known.refused.contains(row.id) {", "        for row in rows {"),
    "H2 the move home waits upWait(0) with no failure": ("        if let last = lastAttempt, failures > 0 { due = max(due, last + upWait(failures: failures)) }",
                                                         "        if let last = lastAttempt { due = max(due, last + upWait(failures: failures)) }"),
    "H3 the move home at > for >=": ("        if let last = lastAttempt, failures > 0 { due = max(due, last + upWait(failures: failures)) }\n        return now >= due ? (true, nil) : (false, due)",
                                     "        if let last = lastAttempt, failures > 0 { due = max(due, last + upWait(failures: failures)) }\n        return now > due ? (true, nil) : (false, due)"),
    "H4 the move home ignores failures": ("        if let last = lastAttempt, failures > 0 { due = max(due, last + upWait(failures: failures)) }",
                                          "        if let last = lastAttempt, failures > 0 { due = max(due, last + moveAfter) }"),
    "H5 the move home at once, not after 2 s listed": ("        guard let since = listedSince else { return (false, nil) }\n        var due = since + moveAfter\n        if let last = lastAttempt, failures > 0 {",
                                                       "        guard let since = listedSince else { return (false, nil) }\n        var due = since\n        if let last = lastAttempt, failures > 0 {"),
    "H6 the move home backs off from the listing, not the last try": ("        if let last = lastAttempt, failures > 0 { due = max(due, last + upWait(failures: failures)) }",
                                                                     "        if let last = lastAttempt, failures > 0 { due = max(due, since + upWait(failures: failures)) }"),
    # moveHomeTrust (the merge with pairing at home): pinned TLS to the saved key only
    "H7 the move home takes whatever a dial would": ("tap: false, newKey: newKey) == .pinned\n        else { return nil }",
                                                     "tap: false, newKey: newKey) != .updateSill\n        else { return nil }"),
    "H8 the move home dials a plain door": ("        guard homeDial(door: door, saved: true, revoked: revoked, homeTLS: true,",
                                            "        guard door == .plain || homeDial(door: door, saved: true, revoked: revoked, homeTLS: true,"),
    "H9 a Mac that removed this device moved home": ("homeDial(door: door, saved: true, revoked: revoked, homeTLS: true, debug: false, tap: false",
                                                    "homeDial(door: door, saved: true, revoked: false, homeTLS: true, debug: false, tap: false"),
    "H10 a Mac with a new key moved home": ("tap: false, newKey: newKey) == .pinned\n        else { return nil }",
                                           "tap: false, newKey: false) == .pinned\n        else { return nil }"),
    "H11 the move home takes any key": ("        return sessionTrust(.pinned, savedPin: savedPin)\n    }\n\n    /// Whether the network connection a move opened",
                                       "        return sessionTrust(.anyKey, savedPin: savedPin)\n    }\n\n    /// Whether the network connection a move opened"),
    # moveHomeRow and HomeRows (the merge's review, 2026-10-08): the move home chooses and refuses by row
    "H12 a door without a pinned dial ends the look": ("trust = moveHomeTrust(door: row.door, revoked: revoked, newKey: newKey, savedPin: savedPin) else { continue }",
                                                       "trust = moveHomeTrust(door: row.door, revoked: revoked, newKey: newKey, savedPin: savedPin) else { break }"),
    "H13 the move home's tries ignored": ("            if best == nil || tries < best!.tries { best = (row.id, trust, tries) }",
                                          "            if best == nil { best = (row.id, trust, tries) }"),
    "H14 the most tries first": ("            if best == nil || tries < best!.tries { best = (row.id, trust, tries) }",
                                 "            if best == nil || tries > best!.tries { best = (row.id, trust, tries) }"),
    "H15 a tie to the later row": ("            if best == nil || tries < best!.tries { best = (row.id, trust, tries) }",
                                   "            if best == nil || tries <= best!.tries { best = (row.id, trust, tries) }"),
    "H16 a refusal outlives its row": ("HomeRows(tries: tries.filter { listed.contains($0.key) }, refused: refused.intersection(listed))",
                                       "HomeRows(tries: tries.filter { listed.contains($0.key) }, refused: refused)"),
    "H17 tries outlive their row": ("HomeRows(tries: tries.filter { listed.contains($0.key) }, refused: refused.intersection(listed))",
                                    "HomeRows(tries: tries, refused: refused.intersection(listed))"),
    "H18 the first row whatever it is": ("        var best: (id: String, trust: HomeTrust, tries: Int)?\n        for row in rows where",
                                         "        var best: (id: String, trust: HomeTrust, tries: Int)?\n        for row in rows.prefix(1) where"),
    # Pairing at home (docs/home-pairing-plan.md, step 4): sessions and pairing at home over TLS (home.swift).
    "S4 pin: an open door's first connection plain": ("        case .open(nil): return .anyKey", "        case .open(nil): return .plainTCP"),
    "S4 pin: an open session's later connections take any key": ("        case .open(let seen?): return .key(seen)", "        case .open(let seen?): return seen.isEmpty ? .key(seen) : .anyKey"),
    "S4 pin: a saved Mac's session takes any key": ("        case .saved(let pin): return .key(pin)", "        case .saved(let pin): return pin.isEmpty ? .key(pin) : .anyKey"),
    "S4 tls: an open session counted as plain": ("        var tls: Bool { self != .plain }", "        var tls: Bool { if case .saved = self { return true }; return false }"),
    "S4 sessionTrust: an open door dialed plain": ("        case .anyKey: return .open(seen: nil)", "        case .anyKey: return .plain"),
    "S4 sessionTrust: a saved Mac without a readable pin dialed with any key": ("        case .pinned: return savedPin.map { .saved(pin: $0) }", "        case .pinned: return savedPin.map { .saved(pin: $0) } ?? .open(seen: nil)"),
    "S4 sessionTrust: the ask starts a session": ("        case .ask, .updateSill, .waitForTap: return nil", "        case .ask: return .open(seen: nil)\n        case .updateSill, .waitForTap: return nil"),
    "S4 sessionTrust: a Mac too old dialed plain": ("        case .ask, .updateSill, .waitForTap: return nil", "        case .updateSill: return .plain\n        case .ask, .waitForTap: return nil"),
    "S4 readyWith: a later connection's key replaces the first": ("        if case .open(nil) = trust, let fingerprint { return .open(seen: fingerprint) }", "        if case .open = trust, let fingerprint { return .open(seen: fingerprint) }"),
    "S4 readyWith: an open session never keeps its key": ("        if case .open(nil) = trust, let fingerprint { return .open(seen: fingerprint) }\n", ""),
    "S4 homeEnd: a plain door's goodbye read as removed": ("        guard let trust, trust.tls else { return .other }", "        guard let trust else { return .other }"),
    "S4 homeEnd: removed not read": ("        if goodbye == \"removed\" { return .removed }\n", ""),
    "S4 homeEnd: pairingRequired not read": ("        if goodbye == \"pairingRequired\" { return .pairingRequired }\n", ""),
    "S4 homeEnd: a TLS error beside another goodbye": ("        guard goodbye == nil, let tls else { return .other }", "        guard let tls else { return .other }"),
    "S4 homeEnd: a refused key never revokes": ("            if keyRefused.contains(tls) { return .removed }\n", ""),
    "S4 homeEnd: a pin failure not told": ("            return tls == pinRefused ? .wrongKey : .other", "            return .other"),
    "S4 homeEnd: an open session's refused key read as removed": ("            return keyRefused.contains(tls) ? .pairingRequired : .other", "            return keyRefused.contains(tls) ? .removed : .other"),
    "S4 homeEnd: -9829 not a refusal": ("    static let keyRefused: Set<Int32> = [-9825, -9829]", "    static let keyRefused: Set<Int32> = [-9825]"),
    "S4 nextPinnedRow: a tried row again": ("        rows.first { $0.macID == macID && !tried.contains($0.id) }?.id", "        rows.first { $0.macID == macID }?.id"),
    "S4 nextPinnedRow: any row, tagged or not": ("        rows.first { $0.macID == macID && !tried.contains($0.id) }?.id", "        rows.first { ($0.macID == macID || $0.macID == nil) && !tried.contains($0.id) }?.id"),
    "S4 askAnswer: the cable's ok without the device's claim": ("            guard method == \"cable\", askedCable, !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }", "            guard method == \"cable\", !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }"),
    "S4 askAnswer: any ok taken": ("            guard method == \"cable\", askedCable, !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }", "            guard askedCable, !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }"),
    "S4 askAnswer: another Mac's ID taken": ("            guard method == \"cable\", askedCable, !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }", "            guard method == \"cable\", askedCable, !hasProof, recognitionKeyBytes == 32 else { return .invalid }"),
    "S4 askAnswer: an ok with a proof taken": ("            guard method == \"cable\", askedCable, !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }", "            guard method == \"cable\", askedCable, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }"),
    "S4 askAnswer: any recognition key": ("            guard method == \"cable\", askedCable, !hasProof, macIDMatches, recognitionKeyBytes == 32 else { return .invalid }", "            guard method == \"cable\", askedCable, !hasProof, macIDMatches, recognitionKeyBytes != nil else { return .invalid }"),
    "S4 askAnswer: shown read as openOnMac": ("        case \"shown\"?: return .shown", "        case \"shown\"?: return .openOnMac"),
    "S4 askAnswer: locked read as refused": ("        case \"locked\"?: return .locked\n", ""),
    "S4 askAnswer: busy unbounded": ("        case \"busy\"?: return .busy(min(max(retryAfter ?? 1, 0.2), 10))", "        case \"busy\"?: return .busy(retryAfter ?? 1)"),
    "S4 askAnswer: an unknown reason read as shown": ("        default: return .refused\n        }\n    }\n\n    /// What the home card says", "        default: return .shown\n        }\n    }\n\n    /// What the home card says"),
    "S4 linkRows: the asked key goes to every row": ("        if let askedKey, askedKey == linkKey { return nil }\n", ""),
    "S4 linkRows: plain doors dialed": ("        return rows.filter { $0.door != .plain && !(askedKey != nil && $0.id == askedRow) }.map(\\.id)", "        return rows.filter { !(askedKey != nil && $0.id == askedRow) }.map(\\.id)"),
    "S4 linkRows: the asked row not left out": ("        return rows.filter { $0.door != .plain && !(askedKey != nil && $0.id == askedRow) }.map(\\.id)", "        return rows.filter { $0.door != .plain }.map(\\.id)"),
    "S4 copy: over the cable dropped": ("            cable ? \"Pairing with \\(mac) over the cable\\u{2026}\" : \"Pairing with \\(mac)\\u{2026}\"", "            \"Pairing with \\(mac)\\u{2026}\""),
    "S4 copy: removed says the old remote words": ("        static func removed(mac: String, device: String) -> String { \"\\(mac) removed this \\(device). Tap it to pair again.\" }", "        static func removed(mac: String, device: String) -> String { \"\\(mac) removed this \\(device). To use it again, pair it again.\" }"),
    "S4 copy: openOnMac names no menu": ("\"\\(mac) didn\\u{2019}t show a code. On the Mac, choose Pair iPhone or iPad\\u{2026} in the Sill menu, then tap \\(mac) again.\"", "\"\\(mac) didn\\u{2019}t show a code.\""),
}
caught = 0
for name, (old, new) in MUTANTS.items():
    assert orig.count(old) == 1, f"{name}: pattern found {orig.count(old)} times"
    path = os.path.join(OUT, "mutant.swift")
    open(path, "w").write(orig.replace(old, new))
    b = subprocess.run(["swiftc", "-O", path, os.path.join(SP, "main.swift"), os.path.join(SP, "home.swift"), "-o", os.path.join(OUT, "mutant")],
                       capture_output=True, text=True)
    if b.returncode != 0:
        print(f"{name}: DOES NOT COMPILE\n{b.stderr[:800]}"); continue
    r = subprocess.run([os.path.join(OUT, "mutant")], capture_output=True, text=True)
    failed = [l[5:] for l in r.stdout.splitlines() if l.startswith("FAIL")]
    ok = r.returncode != 0
    caught += ok
    print(f"{'caught' if ok else 'MISSED'} {name}: {len(failed)} failing, e.g. {failed[:2]}")
print(f"{caught} of {len(MUTANTS)} mutants caught")
sys.exit(0 if caught == len(MUTANTS) else 1)
